name: instadamiolandafinal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.14.1
  firebase_storage: ^11.6.3
  provider: ^6.1.2
  uuid: ^4.1.1
  image_picker: ^1.0.4
  multi_image_picker_view: 2.0.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_dark.png
    - assets/logo_white.png
    - assets/google_icon.png
